using System.Collections.Generic;

namespace StardewClaudeCompanion
{
    public static class FishData
    {
        public static readonly Dictionary<string, string> Names = new()
        {
            { "Sunfish", "太阳鱼" },
            { "SmallmouthBass", "小口黑鲈" },
            { "Bream", "鲂鱼" },
            { "Sardine", "沙丁鱼" },
            { "Flounder", "鲽鱼" },
            { "Seaweed", "海藻" },
            { "Herring", "鲱鱼" },
            { "Anchovy", "鳀鱼" },
            { "SeaJelly", "海母" },
            { "GreenAlgae", "绿藻" },
            { "RiverJelly", "河母" },
            { "Chub", "雅罗鱼" },
            { "Halibut", "大比目鱼" },
            { "Eel", "鳗鱼" },
            { "LargemouthBass", "大口黑鲈" },
            { "Carp", "鲤鱼" },
            { "Bullhead", "牛头鱼" },
            { "Ghostfish", "幽灵鱼" },
            { "WhiteAlgae", "白藻" },
            { "RedMullet", "红鲻鱼" },
            { "Pike", "梭鱼" },
            { "RedSnapper", "红鲷鱼" },
            { "Tuna", "金枪鱼" },
            { "Tilapia", "罗非鱼" },
            { "Dorado", "多拉多鱼" },
            { "Shad", "西鲱" },
            { "Goby", "虾虎鱼" },
            { "RainbowTrout", "虹鳟鱼" },
            { "Shrimp", "虾" },
            { "Clam", "蛤蜊" },
            { "Oyster", "牡蛎" },
            { "Salmon", "鲑鱼" },
            { "SeaCucumber", "海参" },
            { "Albacore", "长鳍金枪鱼" },
            { "MidnightCarp", "午夜鲤鱼" },
            { "Lobster", "龙虾" },
            { "Cockle", "鸟蛤" },
            { "Crayfish", "小龙虾" },
            { "Periwinkle", "滨螺" },
            { "Catfish", "鲶鱼" },
            { "Walleye", "沃尔鱼" },
            { "Angler", "鮟鱇鱼" },
            { "CaveJelly", "洞穴母" },
            { "Lingcod", "长鳕" },
            { "Perch", "鲈鱼" },
            { "TigerTrout", "虎鳟鱼" },
            { "Squid", "鱿鱼" },
            { "ScorpionCarp", "蝎子鲤鱼" },
            { "Sandfish", "沙鱼" },
            { "Glacierfish", "冰川鱼" },
            { "Sturgeon", "鲟鱼" },
            { "Snail", "蜗牛" },
            { "Pufferfish", "河豚" },
            { "Woodskip", "林跳鱼" },
            { "Mussel", "淡菜" },
            { "Crab", "螃蟹" },
            { "IcePip", "冰鱼" },
            { "SuperCucumber", "超级海参" },
            { "LavaEel", "熔岩鳗" },
            { "MutantCarp", "变异鲤鱼" },
            { "VoidSalmon", "虚空鲑鱼" },
            { "Lionfish", "狮子鱼" },
            { "MidnightSquid", "午夜鱿鱼" },
            { "SpookFish", "幽灵鱼" },
            { "Blobfish", "水滴鱼" },
            { "Octopus", "章鱼" },
            { "BlueDiscus", "蓝盘丽鱼" },
            { "Legend", "传说鱼" },
            { "Stingray", "黄貂鱼" },
        };
    }
}